select * from customer limit 20

--1 total revenue generated by male vs female customer 
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--2 which customers used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount)FROM customer);

-- 3 which of the top 5 products with the highest average review rating?
SELECT item_purchased,
AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

--4 compare the average purchase amounts between standard and express shipping?
SELECT shipping_type,
AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--5 do subscribed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--6 which 5 products have the highest percentage of purchages with discount applied ?
SELECT item_purchased,
COUNT(*) AS total_purchases,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
